import PySimpleGUI as sg

#GUI Menu window
layout_menu = [[sg.Text('SOUP', text_color='black')],
          [sg.Checkbox('Black Bean Soup', key='black_bean_soup', size=(18, 1)), sg.Checkbox('Potato Soup', key='potato_soup', size=(18, 1)), sg.Checkbox('French Onion Soup', key='french_onion_soup', size=(18, 1))],
          [sg.Checkbox('Zuppa Toscana Soup', key='zuppa_toscana_soup', size=(18, 1)), sg.Checkbox('Stuffed Pepper Soup', key='stuffed_pepper_soup', size=(18, 1)), sg.Checkbox('Chicken Wild Rice Soup', key='chicken_wild_rice_soup', size=(22, 1))],
          [sg.Checkbox('Lasagna Soup', key='lasagna_soup', size=(18, 1)), sg.Checkbox('Chicken Tortilla Soup', key='chicken_tortilla_soup', size=(18, 1))],
          [sg.Text('MEAT', text_color='black')],
          [sg.Checkbox('Steak', key='steak', size=(10, 1)), sg.Checkbox('Burgers', key='burgers', size=(10, 1)), sg.Checkbox('Pork Chops', key='pork_chops', size=(10, 1)), sg.Checkbox('Chicken', key='chicken', size=(10, 1)), sg.Checkbox('Fish', key='fish', size=(10, 1))],
          [sg.Text('MEXICAN', text_color='black')],
          [sg.Checkbox('Steak Fajitas', key='steak_fajitas', size=(18, 1)), sg.Checkbox('Chicken Fajitas', key='chicken_fajitas', size=(18, 1)), sg.Checkbox('Tacos', key='tacos', size=(18, 1))],
          [sg.Checkbox('Burrito Bowls', key='burrito_bowls', size=(18, 1)), sg.Checkbox('Enchiladas', key='enchiladas', size=(18, 1)), sg.Checkbox('Quesadillas', key='quesadillas', size=(18, 1))],
          [sg.Text('HANDHELD', text_color='black')],
          [sg.Checkbox('BLT', key='blt', size=(15, 1)), sg.Checkbox('BBQ', key='bbq', size=(15, 1)), sg.Checkbox('Lettuce Wraps', key='lettuce_wraps', size=(15, 1)), sg.Checkbox('Brats', key='brats', size=(15, 1))],
          [sg.Text('INDIAN', text_color='black')],
          [sg.Checkbox('Butter Chicken', key='butter_chicken', size=(18, 1)), sg.Checkbox('Chicken w/Yellow Rice', key='chicken_yellow_rice', size=(20, 1)), sg.Checkbox('Tikka Masala', key='tikka_masala', size=(18, 1))],
          [sg.Text('DISHES', text_color='black')],
          [sg.Checkbox('Bean Dish', key='bean_dish', size=(18, 1)), sg.Checkbox('Pot Pie', key='pot_pie', size=(18, 1)), sg.Checkbox('White Chicken Chili', key='white_chicken_chili', size=(18, 1))],
          [sg.Checkbox('Pasta', key='pasta', size=(18, 1)), sg.Checkbox('Steak Stir Fry', key='steak_stir_fry', size=(18, 1)), sg.Checkbox('Beef Stew', key='beef_stew', size=(18, 1))],
          [sg.Checkbox('Gumbo', key='gumbo', size=(18, 1)), sg.Checkbox('Basil Chicken Stir Fry', key='basil_chicken_stir_fry', size=(18, 1)), sg.Checkbox('Pizza', key='pizza', size=(18, 1))],
          [sg.Checkbox('Blackened Chicken', key='blackened_chicken', size=(18, 1)), sg.Checkbox('Salmon w/Garlic+Dijon', key='salmon_garlic_dijon', size=(22, 1))],
          [sg.Checkbox('Chili', key='chili', size=(18, 1))],
          [sg.Submit(tooltip='Submit'), sg.Cancel()]]

#GUI Staples window
layout_staples = [[sg.Text('FRUIT', text_color='black')],
            [sg.Checkbox('Strawberries', key='strawberries', size=(18, 1)), sg.Checkbox('Raspberries', key='raspberries', size=(18, 1)), sg.Checkbox('Grapes', key='grapes', size=(18, 1))],
            [sg.Checkbox('Lemons', key='lemons', size=(18, 1)), sg.Checkbox('Bananas', key='bananas', size=(18, 1)), sg.Checkbox('Green Apples', key='green_apples', size=(18, 1))],
            [sg.Checkbox('Limes', key='limes', size=(18, 1))],
            [sg.Text('PRODUCE', text_color='black')],
            [sg.Checkbox('Mini Cukes', key='mini_cukes', size=(18, 1)), sg.Checkbox('Cherubs', key='cherubs', size=(18, 1))],
            [sg.Text('MEAT', text_color='black')],
            [sg.Checkbox('Hot Dogs', key='hot_dogs', size=(18, 1)), sg.Checkbox('Bacon', key='bacon', size=(18, 1)), sg.Checkbox('Sausage', key='sausage', size=(18, 1))],
            [sg.Checkbox('Landjaegers', key='landjaegers', size=(18, 1)), sg.Checkbox('Summer Sausage', key='summer_sausage', size=(18, 1))],
            [sg.Text('CHEESE', text_color='black')],
            [sg.Checkbox('Jalapeno Meunster', key='jalapeno_meunster', size=(18, 1)), sg.Checkbox('Feta', key='feta', size=(18, 1)), sg.Checkbox('Cheddar', key='cheddar', size=(18, 1))],
            [sg.Checkbox('Swiss', key='swiss', size=(18, 1)), sg.Checkbox('Mozzarella', key='mozzarella', size=(18, 1)), sg.Checkbox('Colby', key='colby', size=(18, 1))],
            [sg.Checkbox('Baby Swiss', key='baby_swiss', size=(18, 1)), sg.Checkbox('Spreadable Cheese', key='spreadable_cheese', size=(18, 1)), sg.Checkbox('Parmesean(block)', key='parmesean_block', size=(18, 1))],
            [sg.Checkbox('Parmesean(grated)', key='parmesean_grated', size=(18, 1))],
            [sg.Text('DAIRY', text_color='black')],
            [sg.Checkbox('Milk', key='milk', size=(18, 1)), sg.Checkbox('Eggs', key='eggs', size=(18, 1)), sg.Checkbox('Butter', key='butter', size=(18, 1))],
            [sg.Checkbox('Yogurt(tub)', key='yogurt_tub', size=(18, 1)), sg.Checkbox('Yogurt(pouch)', key='yogurt_pouch', size=(18, 1)), sg.Checkbox('Yogurt(drink)', key='yogurt_drink', size=(18, 1))],
            [sg.Checkbox('Sour Cream', key='sour_cream', size=(18, 1)), sg.Checkbox('Creamer', key='creamer', size=(18, 1)), sg.Checkbox('Yogurt(greek)', key='yogurt_greek', size=(18, 1))],
            [sg.Checkbox('Cottage Cheese', key='cottage_cheese', size=(18, 1)), sg.Checkbox('Orange Juice', key='orange_juice', size=(18, 1)), sg.Checkbox('Lemonade', key='lemonade', size=(18, 1))],
            [sg.Text('FROZEN', text_color='black')],
            [sg.Checkbox('Waffles', key='waffles', size=(18, 1))],
            [sg.Text('GLUTEN FREE', text_color='black')],
            [sg.Checkbox('Bread', key='bread', size=(18, 1)), sg.Checkbox('Pretzels', key='pretzels', size=(18, 1))],
            [sg.Text('DRY GOODS', text_color='black')],
            [sg.Checkbox('Coffee', key='coffee', size=(18, 1))],
            [sg.Text('CEREAL', text_color='black')],
            [sg.Checkbox('Corn Chex', key='corn_chex', size=(18, 1)), sg.Checkbox('Honey Chex', key='honey_chex', size=(18, 1)), sg.Checkbox('Honey Nut Cheerios', key='honey_cheerios', size=(18, 1))],
            [sg.Checkbox('Lucky Charms', key='lucky_charms', size=(18, 1)), sg.Checkbox('Reese\'s Puffs', key='reeses_puffs', size=(18, 1)), sg.Checkbox('Fruit Loops', key='fruit_loops', size=(18, 1))],
            [sg.Checkbox('Captain Crunch', key='captain_crunch', size=(18, 1)), sg.Checkbox('Cinnamon Toast Crunch', key='cinnamon_toast_crunch', size=(18, 1))],
            [sg.Text('SNACKS', text_color='black')],
            [sg.Checkbox('Almonds', key='almonds', size=(18, 1)), sg.Checkbox('Pistachios', key='pistachios', size=(18, 1)), sg.Checkbox('Saltines', key='saltines', size=(18, 1))],
            [sg.Checkbox('Graham Crackers', key='graham_crackers', size=(18, 1))],
            [sg.Submit(tooltip='Submit'), sg.Cancel()]]

#GUI CostCo window
layout_costco = [[sg.Checkbox('Sparkling Water', key='sparkling_water', size=(18, 1)), sg.Checkbox('Mineral Water', key='mineral_water', size=(18, 1)), sg.Checkbox('Bulk Fruit', key='bulk_fruit', size=(18, 1))],
            [sg.Checkbox('Brussels Sprouts', key='brussels_sprouts', size=(18, 1)), sg.Checkbox('Olive Oil', key='olive_oil', size=(18, 1)), sg.Checkbox('Kids Snacks', key='kids_snacks', size=(22, 1))],
            [sg.Checkbox('Paper Towels', key='paper_towels', size=(18, 1)), sg.Checkbox('Toilet Paper', key='toilet_paper', size=(18, 1)), sg.Checkbox('Chicken Nuggets', key='chicken_nuggets', size=(18, 1))],
            [sg.Checkbox('Baby Wipes', key='baby_wipes', size=(18, 1)), sg.Checkbox('Kleenex', key='kleenex', size=(18, 1)), sg.Checkbox('Sangria', key='sangria', size=(18, 1))],
            [sg.Checkbox('Dishwasher Soap', key='dishwasher_soap', size=(18, 1)), sg.Checkbox('Garbage Bags', key='garbage_bags', size=(18, 1)), sg.Checkbox('Margarita', key='margarita', size=(18, 1))],
            [sg.Checkbox('Irish Butter', key='irish_butter', size=(18, 1)), sg.Checkbox('Frozen Pizza', key='frozen_pizza', size=(18, 1)), sg.Checkbox('Seltzers', key='seltzers', size=(18, 1))],
            [sg.Submit(tooltip='Submit'), sg.Cancel()]]